CREATE TRIGGER SP_NACIONAL
ON NACIONAL
FOR INSERT
AS
	DECLARE @IDPAQUETE NUMERIC(5)
	DECLARE @INTER NUMERIC(5)
	SET @IDPAQUETE = (SELECT CODIGO_PAQUETE FROM inserted)
	SET @INTER = (SELECT CODIGO_PAQUETE FROM INTERNACIONAL WHERE CODIGO_PAQUETE = @IDPAQUETE)

	IF (@INTER IS NOT NULL)
	BEGIN
		PRINT 'ESTE PAQUETE ES ENVIO INTERNACIONAL'
		ROLLBACK TRANSACTION
	END

--PRUEBA, ESE CODIGO ESTA EN INTERNACIONAL
INSERT INTO NACIONAL VALUES ('67890','ACAPULCO','AAAAAAAAAAAAA',1);
--PARA VER SI NO SE INGRESO
SELECT * FROM NACIONAL

CREATE TRIGGER SP_INTERNACIONAL
ON INTERNACIONAL
FOR INSERT
AS
	DECLARE @IDPAQUETE NUMERIC(5)
	DECLARE @NACIONAL NUMERIC(5)
	SET @IDPAQUETE = (SELECT CODIGO_PAQUETE FROM inserted)
	SET @NACIONAL = (SELECT CODIGO_PAQUETE FROM NACIONAL WHERE CODIGO_PAQUETE = @IDPAQUETE)

	IF (@NACIONAL IS NOT NULL)
	BEGIN
		PRINT 'ESTE PAQUETE ES ENVIO NACIONAL'
		ROLLBACK TRANSACTION
	END

--PRUEBA, ESE CODIGO ESTA EN NACIONAL
INSERT INTO INTERNACIONAL VALUES ('12345','AMERICAN AIRLINES','5-1-23',3)
	--PARA VER SI NO SE INGRESO
SELECT * FROM INTERNACIONAL



CREATE OR ALTER TRIGGER SP_CARGA
ON CAMION
FOR INSERT
AS
	DECLARE @PESO NUMERIC(6)
	SET @PESO = (SELECT CARGA_MAXIMA FROM inserted)

	IF (@PESO < 250)
	BEGIN
		PRINT 'El camion no cumple con la carga minima solicitada'
		ROLLBACK TRANSACTION
	END
	ELSE 
		IF (@PESO > 1250)
		BEGIN
			PRINT 'El camion sobrepasa la carga maxima permitida'
			ROLLBACK TRANSACTION
		END
		ELSE
			COMMIT

--PRUEBA
INSERT INTO CAMION VALUES('ZZZ-999',2500,'CDMX')
INSERT INTO CAMION VALUES('ZZZ-999',249,'CDMX')



CREATE OR ALTER TRIGGER SP_NUEVO_ENVIO
ON NACIONAL
FOR INSERT
AS
	DECLARE @CIUDAD VARCHAR(20)
	DECLARE @CDEXISTE VARCHAR(20)
	SET @CIUDAD = (SELECT CIUDAD_DESTINO FROM inserted)
	SET @CDEXISTE = (SELECT CIUDAD_DESTINO FROM CIUDADES WHERE CIUDAD_DESTINO = @CIUDAD)
	IF (@CDEXISTE IS NULL)
	BEGIN
		INSERT INTO CIUDADES VALUES (@CIUDAD, 1)
		COMMIT
	END
	ELSE
	BEGIN
		UPDATE CIUDADES
		SET NUM_ENVIOS = NUM_ENVIOS + 1
		WHERE CIUDAD_DESTINO = @CIUDAD
		COMMIT
	END