include<p16f877a.inc>

valor1 equ h'21' 
valor2 equ h'22' 
valor3 equ h'23' 
cte1 equ 0f0h 
cte2 equ 12h 
cte3 equ 60h 
ORG 0
GOTO INICIO 
ORG 5

;Configura a B como entrada y lo pone en cero 
INICIO
	CLRF PORTA ;LIMPIA EL PUERTOS A Y B
	CLRF PORTB
	BSF STATUS,RP0 ;CAMBIA AL BANCO 01
	CLRF TRISB ;CONFIGURA LOS PINES DEL PUERTO B COMO SALIDAS
	MOVLW 0X06
	MOVWF ADCON1 ;CONFIGURA LOS PINES DEL PUERTO A Y E COMO I/O DIGITALES
	MOVLW 0X3F
	MOVWF TRISA ;PUERTO A COMO ENTRADAS
	BCF STATUS,RP0 ;REGRESA AL BANCO 0 
PRINCIPAL:	;Programa principal 
	MOVF PORTA,0
	XORLW B'00000111' 
	ADDWF PCL,F
	GOTO APAGADOS	;No ejecuta nada
	GOTO PRIMERA ;Girar en sentido horario 5 segundos
	GOTO SEGUNDA ;Girar en sentido antihorario 10 segundos 
	GOTO TERCERA ;Girar 5 veces en sentido horarios
	GOTO CUARTA	;Girar en sentido antihorario 10 veces 
	GOTO VACIO	;Nada
	GOTO VACIO	;Nada
	GOTO VACIO	;Nada 
APAGADOS:
CLRF PORTB 
GOTO PRINCIPAL
PRIMERA:
CALL GIROHORARIO 
CALL GIROHORARIO 
CALL GIROHORARIO 
CALL GIROHORARIO 
CALL GIROHORARIO 
GOTO PRINCIPAL
SEGUNDA:
CALL GIROANTIHORARIO 
CALL GIROANTIHORARIO 
CALL GIROANTIHORARIO 
CALL GIROANTIHORARIO 
CALL GIROANTIHORARIO 
CALL GIROANTIHORARIO 
CALL GIROANTIHORARIO 
CALL GIROANTIHORARIO 
CALL GIROANTIHORARIO 
CALL GIROANTIHORARIO 
GOTO PRINCIPAL
TERCERA:
CALL GIROHORARIO 
CALL GIROHORARIO 
CALL GIROHORARIO 
CALL GIROHORARIO 
CALL GIROHORARIO 
GOTO PRINCIPAL
CUARTA:
CALL GIROANTIHORARIO 
CALL GIROANTIHORARIO 
CALL GIROANTIHORARIO 
CALL GIROANTIHORARIO 
CALL GIROANTIHORARIO 
CALL GIROANTIHORARIO 
CALL GIROANTIHORARIO 
CALL GIROANTIHORARIO 
CALL GIROANTIHORARIO 
CALL GIROANTIHORARIO 
GOTO PRINCIPAL
VACIO:
CLRF PORTB 
GOTO PRINCIPAL
GIROHORARIO:	;Giro horario de 1 segundo 
MOVLW B'10000000'
MOVWF PORTB
CALL retardo 
MOVLW B'01000000'
MOVWF PORTB
CALL retardo 
MOVLW B'00100000'
MOVWF PORTB
CALL retardo 
MOVLW B'00010000'
MOVWF PORTB
CALL retardo
GIROANTIHORARIO:	;Giro antihorario de 1 segundo 
MOVLW B'00010000'
MOVWF PORTB
CALL retardo 
MOVLW B'00100000' 
MOVWF PORTB
CALL retardo 
MOVLW B'01000000'
MOVWF PORTB
CALL retardo 
MOVLW B'10000000'
MOVWF PORTB
CALL retardo
retardo:
MOVLW cte1 
MOVWF valor1
tres
MOVLW cte2 
MOVWF valor2
dos
MOVLW cte3 
MOVWF valor3 
uno	
DECFSZ valor3 
GOTO uno 
DECFSZ valor2 
GOTO dos 
DECFSZ valor1 
GOTO tres 
RETURN
END
