SELECT O.NOMBRE, O.APELLIDO, E.LUGAR_NAC
FROM OBRERO O INNER JOIN ESTADOS E
ON O.ID_EDO = E.ID_EDO;

SELECT M.ID_MAQUINA, AVG(C.SUELDO)
FROM MAQUINA M INNER JOIN OBRERO O
ON M.ID_MAQUINA = O.ID_MAQUINA
INNER JOIN CLASIFICACION C
ON C.ID_CLASIFICACION = O.ID_CLASIFICACION
GROUP BY M.ID_MAQUINA;

SELECT * 
FROM CLASIFICACION C INNER JOIN OBRERO O 
ON C.ID_CLASIFICACION = O.ID_CLASIFICACION
INNER JOIN OBRA OA 
ON OA.ID_OBRA = O.ID_OBRA
INNER JOIN ESTADOS E 
ON O.ID_EDO = E.ID_EDO
INNER JOIN MAQUINA M 
ON O.ID_MAQUINA = M.ID_MAQUINA;

SELECT NOMBRE, APELLIDO
FROM OBRERO
WHERE FECHA_INGRESO >
(
    SELECT FECHA_INGRESO
    FROM OBRERO
    WHERE NOMBRE = 'Francisco' AND
    APELLIDO = 'Serrano'
);

SELECT N.N_SEM, C.TIPO, AVG(CANT_HORA)
FROM NOMINA N INNER JOIN CLASIFICACION C
ON N.ID_CLASIFICACION = C.ID_CLASIFICACION
GROUP BY N.N_SEM, C.TIPO
ORDER BY N.N_SEM ASC;

SELECT ID_EDO, COUNT(ID_OBRERO) NumObrero
FROM OBRERO
GROUP BY ID_EDO; 

SELECT NO_RECIBO
FROM NOMINA
WHERE CANT_HORA =
(
    SELECT CANT_HORA
    FROM NOMINA
    WHERE NO_RECIBO = 1472
);

SELECT N_SEM, AVG(CANT_HORA)
FROM NOMINA
GROUP BY N_SEM
HAVING AVG(CANT_HORA) >
(
    SELECT AVG(CANT_HORA)
    FROM NOMINA
);

CREATE VIEW PromXMaq AS(
    SELECT M.ID_MAQUINA, AVG(C.SUELDO) Promedio
    FROM MAQUINA M INNER JOIN OBRERO O
    ON M.ID_MAQUINA = O.ID_MAQUINA
    INNER JOIN CLASIFICACION C
    ON C.ID_CLASIFICACION = O.ID_CLASIFICACION
    GROUP BY M.ID_MAQUINA
);

CREATE VIEW ObreroXEdo AS(
    SELECT ID_EDO, COUNT(ID_OBRERO) NumObrero
    FROM OBRERO
    GROUP BY ID_EDO 
);

CREATE VIEW LUGAR_OBRERO AS(
    SELECT O.NOMBRE, O.APELLIDO, E.LUGAR_NAC
    FROM OBRERO O INNER JOIN ESTADOS E
    ON O.ID_EDO = E.ID_EDO
);
